import "./audio";
import "./arg";
import "./data";
import "./event";
import "./filesystem";
import "./font";
import "./graphics";
import "./image";
import "./joystick";
import "./keyboard";
import "./math";
import "./mouse";
import "./path";
import "./physics";
import "./sound";
import "./system";
import "./thread";
import "./timer";
import "./touch";
import "./video";
import "./window";

declare module "love" {
    export const audio: typeof import("love.audio");
    export const data: typeof import("love.data");
    export const event: typeof import("love.event");
    export const filesystem: typeof import("love.filesystem");
    export const font: typeof import("love.font");
    export const graphics: typeof import("love.graphics");
    export const image: typeof import("love.image");
    export const joystick: typeof import("love.joystick");
    export const keyboard: typeof import("love.keyboard");
    export const math: typeof import("love.math");
    export const mouse: typeof import("love.mouse");
    export const physics: typeof import("love.physics");
    export const sound: typeof import("love.sound");
    export const system: typeof import("love.system");
    export const thread: typeof import("love.thread");
    export const timer: typeof import("love.timer");
    export const touch: typeof import("love.touch");
    export const video: typeof import("love.video");
    export const window: typeof import("love.window");
}
