/**
 * Documented at
 * https://love2d.org/wiki/love
 * Obtained 2019/05/21
 */
love;
love.getVersion;
love.hasDeprecationOutput;
love.isVersionCompatible;
love.setDeprecationOutput;
love.directorydropped;
love.draw;
love.errorhandler;
love.filedropped;
love.focus;
love.keypressed;
love.keyreleased;
love.load;
love.lowmemory;
love.mousefocus;
love.mousemoved;
love.mousepressed;
love.mousereleased;
love.quit;
love.resize;
love.run;
love.textedited;
love.textinput;
love.threaderror;
love.touchmoved;
love.touchpressed;
love.touchreleased;
love.update;
love.visible;
love.wheelmoved;
love.gamepadaxis;
love.gamepadpressed;
love.gamepadreleased;
love.joystickadded;
love.joystickaxis;
love.joystickhat;
love.joystickpressed;
love.joystickreleased;
love.joystickremoved;
