love;
love.window;

love.window.close;
love.window.fromPixels;
love.window.getDPIScale;
love.window.getDesktopDimensions;
love.window.getDisplayCount;
love.window.getDisplayName;
love.window.getFullscreen;
love.window.getFullscreenModes;
love.window.getIcon;
love.window.getMode;
love.window.getPosition;
love.window.getTitle;
love.window.hasFocus;
love.window.hasMouseFocus;
love.window.isDisplaySleepEnabled;
love.window.isMaximized;
love.window.isMinimized;
love.window.isOpen;
love.window.isVisible;
love.window.maximize;
love.window.minimize;
love.window.requestAttention;
love.window.restore;
love.window.setDisplaySleepEnabled;
love.window.setFullscreen;
love.window.setIcon;
love.window.setMode;
love.window.setPosition;
love.window.setTitle;
love.window.showMessageBox;
const buttonList: ButtonList = ["Enter", "Escape"];
buttonList.enterbutton = 1;
buttonList.escapebutton = 2;
love.window.showMessageBox("Title", "Message", buttonList);
love.window.toPixels;
love.window.updateMode;
